In [1]:
import pandas as pd

In [2]:
from sklearn.datasets import load_iris
iris = load_iris()

In [3]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [5]:
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [6]:
df['target'] = iris.target

In [7]:
df.head(10)

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                5.1               3.5  ...               0.2       0
1                4.9               3.0  ...               0.2       0
2                4.7               3.2  ...               0.2       0
3                4.6               3.1  ...               0.2       0
4                5.0               3.6  ...               0.2       0
5                5.4               3.9  ...               0.4       0
6                4.6               3.4  ...               0.3       0
7                5.0               3.4  ...               0.2       0
8                4.4               2.9  ...               0.2       0
9                4.9               3.1  ...               0.1       0

[10 rows x 5 columns]

In [8]:
x = df.drop('target', axis='columns')

In [16]:
x.head(40)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
5                 5.4               3.9                1.7               0.4
6                 4.6               3.4                1.4               0.3
7                 5.0               3.4                1.5               0.2
8                 4.4               2.9                1.4               0.2
9                 4.9               3.1                1.5               0.1
10                5.4               3.7                1.5               0.2
11                4.8               3.4                1.6               0.2
12                4.8               3.0                1.4               0.1
13                4.3               3.0                1.1               0.1
14                5.8               4.0                1.2               0.2
15                5.7               4.4                1.5               0.4
16                5.4               3.9                1.3               0.4
17                5.1               3.5                1.4               0.3
18                5.7               3.8                1.7               0.3
19                5.1               3.8                1.5               0.3
20                5.4               3.4                1.7               0.2
21                5.1               3.7                1.5               0.4
22                4.6               3.6                1.0               0.2
23                5.1               3.3                1.7               0.5
24                4.8               3.4                1.9               0.2
25                5.0               3.0                1.6               0.2
26                5.0               3.4                1.6               0.4
27                5.2               3.5                1.5               0.2
28                5.2               3.4                1.4               0.2
29                4.7               3.2                1.6               0.2
30                4.8               3.1                1.6               0.2
31                5.4               3.4                1.5               0.4
32                5.2               4.1                1.5               0.1
33                5.5               4.2                1.4               0.2
34                4.9               3.1                1.5               0.2
35                5.0               3.2                1.2               0.2
36                5.5               3.5                1.3               0.2
37                4.9               3.6                1.4               0.1
38                4.4               3.0                1.3               0.2
39                5.1               3.4                1.5               0.2

In [9]:
y = df.target

Creating the SVC model:

In [ ]:
from sklearn.svm import SVC
model = SVC(kernel = 'rbf', C=30,gamma='auto')

#### Lets Revise Cross Validation Code:

In [ ]:
from sklearn.model_selection import KFold

kf = KFold(n_splits=5)

for train_index,test_index in kf.split(x,y):
    #print(train_index,test_index)
    scores = []
    x_train,x_test,y_train,y_test = x.iloc[train_index],x.iloc[test_index], y.iloc[train_index],y.iloc[test_index]  #iloc is ot locatet the rows in the dataframe
    model.fit(x_train,y_train)
    print(model.score(x_test,y_test))
    
    

1.0
1.0
0.8333333333333334
0.9333333333333333
0.7


### Now Lets do with cross_val_score,the inbuilt function which directly gives the Result:

In [26]:
from sklearn.model_selection import cross_val_score
cross_val_score(SVC(kernel='rbf', gamma ='auto', C=10), x,y, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [28]:
cross_val_score(SVC(kernel='rbf', gamma ='auto', C=30), x,y,cv=5)

array([0.96666667, 1.        , 0.9       , 0.93333333, 1.        ])

In [27]:
cross_val_score(SVC(kernel='rbf', gamma ='auto', C=40), x,y,cv=5)

array([1.        , 0.96666667, 0.9       , 0.93333333, 1.        ])

For the above method, we can find the avg score by taking avewrage

#### The above method seems time consuming as its more manual and repetitive, there is sklearn library called GridSearchCV to do it!

In [29]:
from sklearn.model_selection import GridSearchCV

Syntax: GridSearchCV( model , parameters that yuou wanna cutomize in json like sructure.)

In [ ]:
clf = GridSearchCV(SVC(gamma='auto'), {
    'kernel':['rbf','linear','poly'],
    'C':[10,30,40]
}, cv=5, return_train_score=False) #cv implies how many Cross validation needs to run

In [32]:
clf.fit(x,y)
clf.cv_results_


{'mean_fit_time': array([0.00167994, 0.00142651, 0.00293837, 0.00116105, 0.00123181,
        0.00508909, 0.00137267, 0.00124726, 0.00497994]),
 'std_fit_time': array([2.20458862e-04, 1.65895643e-04, 1.03826850e-03, 5.28561461e-05,
        5.82687593e-05, 3.02053628e-03, 2.10303546e-04, 1.36894758e-04,
        3.17510351e-03]),
 'mean_score_time': array([0.00126634, 0.00111947, 0.00118003, 0.00097528, 0.00096164,
        0.00116463, 0.00091367, 0.00102043, 0.00102296]),
 'std_score_time': array([2.30739653e-04, 1.86899279e-04, 2.67984714e-04, 2.21927339e-04,
        2.16429951e-04, 1.82796033e-04, 4.05545448e-05, 1.34169470e-04,
        1.30708328e-04]),
 'param_C': masked_array(data=[10, 10, 10, 30, 30, 30, 40, 40, 40],
              mask=[False, False, False, False, False, False, False, False,
                    False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'poly', 'rbf', 'linear', 'poly',
                    'rbf', 'linear', 'poly'],
      

In [33]:
CrossValidation_result = pd.DataFrame(clf.cv_results_)
CrossValidation_result

mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.001680      0.000220  ...        0.016330                1
1       0.001427      0.000166  ...        0.038873                2
2       0.002938      0.001038  ...        0.042164                3
3       0.001161      0.000053  ...        0.038873                4
4       0.001232      0.000058  ...        0.048990                4
5       0.005089      0.003021  ...        0.033993                8
6       0.001373      0.000210  ...        0.038873                4
7       0.001247      0.000137  ...        0.048990                4
8       0.004980      0.003175  ...        0.033993                8

[9 rows x 15 columns]

### We dont need to view all the values in the table, we need to view which values of C and Kernel gives optimal result, so:

In [34]:
CrossValidation_result[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       10          rbf         0.980000
1       10       linear         0.973333
2       10         poly         0.966667
3       30          rbf         0.960000
4       30       linear         0.960000
5       30         poly         0.953333
6       40          rbf         0.960000
7       40       linear         0.960000
8       40         poly         0.953333

In [35]:
dir(CrossValidation_result)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__

From the Table we can notice with C= 10 and Kernel = RBF, we are getting the best Result among others

### One of the Problem which happens in GridSearchCV is computation Cost
### To tackle this COmputation Problem sklearn Library comes up with: **RandomizedSearchCV**

In [42]:
from sklearn.model_selection import RandomizedSearchCV
rs= RandomizedSearchCV(SVC(gamma='auto'),{
    'kernel': ['rbf','linear'],
    'C':[1,10,30]
},
cv=5, return_train_score=False, n_iter=3)
rs.fit(x,y)
cv_res = pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]
cv_res


param_C param_kernel  mean_test_score
0       10       linear         0.973333
1        1       linear         0.980000
2       10          rbf         0.980000

In [43]:
rs.best_score_

np.float64(0.9800000000000001)

In [44]:
rs.best_params_

{'kernel': 'linear', 'C': 1}